name: Publish Site to Interwebs

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/publish_www.yaml

jobs:
  schemas-deploy:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
        
      - name: Setup and build with Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
        run: build
        
      - name: Upload files to site
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./dist
          dangerous-clean-slate: true
